"""Top-level package for AI-assisted multi-reference timekeeping utilities."""

from .chrony import ChronyShmSample, ChronyShmWriter
from .fusion import ClockUpdate, HeuristicFusion, Measurement, QualityMeasurement, ReferenceFusion, VirtualClock
from .kalman import ClockKalmanFilter
from .metrics import HoldoverStats, holdover_stats, mtie, tdev
from .time_server import (
    AudioFeatureSensor,
    EnvironmentalSensor,
    GeigerCounterSensor,
    GpsLockSensor,
    GpioPulseSensor,
    LinearInferenceModel,
    LightweightInferenceModel,
    MlVarianceModel,
    NmeaGpsReference,
    NtpReference,
    RtcReference,
    SerialReference,
    SensorAggregator,
    SensorFrame,
    SerialLineSensor,
    SlewDriftDetector,
    TimeServer,
    TimeServerStep,
    open_line_source,
    RadioSnrSensor,
)

__all__ = [
    "ClockUpdate",
    "ClockKalmanFilter",
    "Measurement",
    "QualityMeasurement",
    "ReferenceFusion",
    "HeuristicFusion",
    "VirtualClock",
    "ChronyShmSample",
    "ChronyShmWriter",
    "HoldoverStats",
    "holdover_stats",
    "mtie",
    "tdev",
    "LightweightInferenceModel",
    "LinearInferenceModel",
    "MlVarianceModel",
    "AudioFeatureSensor",
    "EnvironmentalSensor",
    "GeigerCounterSensor",
    "GpsLockSensor",
    "GpioPulseSensor",
    "NmeaGpsReference",
    "NtpReference",
    "RtcReference",
    "SerialReference",
    "RadioSnrSensor",
    "SensorAggregator",
    "SensorFrame",
    "SerialLineSensor",
    "SlewDriftDetector",
    "TimeServer",
    "TimeServerStep",
    "open_line_source",
]
